refactor/sphere-model
torin-asakura/dream-team pull request #121
Opened 2024-02-14 08:27 UTC by Amiditin

Resolves #120 

<details>
<summary>Видео</summary>

[Запись экрана от 14.02.2024 11:25:10.webm](https://github.com/torin-asakura/dream-team/assets/80476878/c0a4c109-f55a-4269-86f6-f70656947af9)
</details>

2024-02-14 08:56 UTC, Nelfimov requested changes
1. файлы с моделью 500Мб, такое будет долго лететь до клиента
2. используй `threejs` для анимации шейдеров https://threejs.org/docs/#examples/en/loaders/GLTFLoader

Материалы:
- https://habr.com/ru/post/591191/
- https://codesandbox.io/embed/exciting-marco-iyy6h

2024-02-14 10:02 UTC, Amiditin commented
> 2\. используй `threejs` для анимации шейдеров https://threejs.org/docs/#examples/en/loaders/GLTFLoader

@Nelfimov  ранешь пытался делать шейдерную анимацию через `threejs`, максимум получалось что-то такое https://github.com/torin-asakura/dream-team/pull/102#issuecomment-1746629734. Если @pussypistolss сможет скинуть анимацию текущей сферы в фомате `.glsl`, то можно будет попробовать подключить  её через `threejs`.

2024-02-14 10:04 UTC, Nelfimov commented
> Если @pussypistolss сможет скинуть анимацию текущей сферы в фомате `.glsl`, то можно будет попробовать подключить её через `threejs`.

Скооперируйтесь пожалуйста с @pussypistolss.

2024-02-14 16:40 UTC, pussypistolss commented
>Если @pussypistolss сможет скинуть анимацию текущей сферы в фомате `.glsl`, то можно будет попробовать подключить её через `threejs`.

У меня не шейдерная анимация, я ее через модификаторы делала. Я изучу еще эту тему, но вряд ли получится сделать так.

2024-02-14 21:41 UTC, TorinAsakura commented
> > Если @pussypistolss сможет скинуть анимацию текущей сферы в фомате `.glsl`, то можно будет попробовать подключить её через `threejs`.
> 
> У меня не шейдерная анимация, я ее через модификаторы делала. Я изучу еще эту тему, но вряд ли получится сделать так.

если у других получилось - то и у нас должно

2024-02-27 13:49 UTC, pussypistolss commented
> ранеше пытался делать шейдерную анимацию через `threejs`, максимум получалось что-то такое [#102 (comment)](https://github.com/torin-asakura/dream-team/pull/102#issuecomment-1746629734). Если @pussypistolss сможет скинуть анимацию текущей сферы в фомате `.glsl`, то можно будет попробовать подключить её через `threejs`.

@Amiditin 

https://github.com/torin-asakura/dream-team/assets/147274591/85e0042f-c0ae-4b09-a4be-c3e5f7e8a5ab

Отредактировала сделанную шейдерную анимацию.
Я делала ее ориентируясь на [видео](https://www.youtube.com/watch?v=OKRqHmjkSwI&t=103s), по которому был сделан гайд на который ты ориентировался, когда делал шейдерную анимацию через `threejs`.
Я не нашла способа импортировать готовую анимацию в код. У тебя есть [та сфера](https://github.com/torin-asakura/dream-team/pull/102#issuecomment-1746629734), которую ты пытался сделать, мне кажется тебе в ручную нужно будет ее отредактировать и сделать похожей на ту, что сделала я сейчас.

2024-02-27 13:59 UTC, TorinAsakura commented
> > ранеше пытался делать шейдерную анимацию через `threejs`, максимум получалось что-то такое [#102 (comment)](https://github.com/torin-asakura/dream-team/pull/102#issuecomment-1746629734). Если @pussypistolss сможет скинуть анимацию текущей сферы в фомате `.glsl`, то можно будет попробовать подключить её через `threejs`.
> 
> @Amiditin
> 
>  IMG_8569-3.MP4 
> 
> Отредактировала сделанную шейдерную анимацию. Я делала ее ориентируясь на [видео](https://www.youtube.com/watch?v=OKRqHmjkSwI&t=103s), по которому был сделан гайд на который ты ориентировался, когда делал шейдерную анимацию через `threejs`. Я не нашла способа импортировать готовую анимацию в код. У тебя есть [та сфера](https://github.com/torin-asakura/dream-team/pull/102#issuecomment-1746629734), которую ты пытался сделать, мне кажется тебе в ручную нужно будет ее отредактировать и сделать похожей на ту, что сделала я сейчас.

а откуда ты пытаешься экспортировать шейдеры в код?

2024-02-27 14:00 UTC, pussypistolss commented
> а откуда ты пытаешься экспортировать шейдеры в код?

Из блендера

2024-02-27 14:17 UTC, Amiditin commented
> Отредактировала сделанную шейдерную анимацию.

@pussypistolss размер сферы прежний?

>  У тебя есть https://github.com/torin-asakura/dream-team/pull/102#issuecomment-1746629734, которую ты пытался сделать, мне кажется тебе в ручную нужно будет ее отредактировать и сделать похожей на ту, что сделала я сейчас.

Те шейдеры для threejs я брал из открытых источников и редактировал только предоставляемые начальные переменные (амплитуды, скороcть, тайминги анимаций), поэтому как воссоздать анимацию как на видео я сейчас не знаю. Вариант с видео точно проигрышный? мы не можем попробовать разные форматы видео, или сделать gif  с прозрачным фоном?

2024-02-27 14:28 UTC, TorinAsakura commented
> > Отредактировала сделанную шейдерную анимацию.
> 
> @pussypistolss размер сферы прежний?
> 
> > У тебя есть [#102 (comment)](https://github.com/torin-asakura/dream-team/pull/102#issuecomment-1746629734), которую ты пытался сделать, мне кажется тебе в ручную нужно будет ее отредактировать и сделать похожей на ту, что сделала я сейчас.
> 
> Те шейдеры для threejs я брал из открытых источников и редактировал только предоставляемые начальные переменные (амплитуды, скороcть, тайминги анимаций), поэтому как воссоздать анимацию как на видео я сейчас не знаю. Вариант с видео точно проигрышный? мы не можем попробовать разные форматы видео, или сделать gif с прозрачным фоном?

видео контейнер с анимацией всегда будет весить **сотни**, к сожалению

поэтому вариант с шейдерной анимацией единственный возможный

вопрос с блендером и трижс я уже разбирал когда-то, надо посидеть, отпишусь

2024-02-27 14:35 UTC, TorinAsakura commented
> > а откуда ты пытаешься экспортировать шейдеры в код?
> 
> Из блендера

https://www.google.com/search?client=safari&rls=en&q=blender+three.js&ie=UTF-8&oe=UTF-8 - топ 10 из гугла, включая офф доку. Как ты могла "не найти"?

2024-02-27 14:53 UTC, pussypistolss commented
> https://www.google.com/search?client=safari&rls=en&q=blender+three.js&ie=UTF-8&oe=UTF-8 - топ 10 из гугла, включая офф доку. Как ты могла "не найти"?

Cкинь ссылки, пожалуйста

2024-02-27 14:53 UTC, TorinAsakura commented
> > https://www.google.com/search?client=safari&rls=en&q=blender+three.js&ie=UTF-8&oe=UTF-8 - топ 10 из гугла, включая офф доку. Как ты могла "не найти"?
> 
> Cкинь ссылки, пожалуйста

я тебе скинул поисковую выдачу. Мне за тебя ещё ссылки подобрать?

2024-02-27 14:54 UTC, TorinAsakura commented
![Снимок экрана 2024-02-27 в 17 53 59](https://github.com/torin-asakura/dream-team/assets/3940885/e1d6ef75-b70f-4b2e-b10c-93043cd98c30)

2024-02-27 14:56 UTC, pussypistolss commented
> я тебе скинул поисковую выдачу. Мне за тебя ещё ссылки подобрать?
Так я не вижу никакой информации про шейдеры, в документации про GLTF формат написано, он не поддерживает шейдеры

2024-02-27 14:57 UTC, jade-smith-rs46 commented
> > я тебе скинул поисковую выдачу. Мне за тебя ещё ссылки подобрать?
> 
> Так я не вижу никакой информации про шейдеры, в документации про GLTF формат написано, он не поддерживает шейдеры

у тебя был вопрос про выгрузку моделей в threejs - я тебе дал её
принцип там везде один и тот же, по этой причине ты не смогла найти доку по выгрузке конкретно анимации, так как эту задачу покрывает дока по выгрузке моделей

2024-02-27 14:59 UTC, TorinAsakura commented
> > я тебе скинул поисковую выдачу. Мне за тебя ещё ссылки подобрать?
> 
> Так я не вижу никакой информации про шейдеры, в документации про GLTF формат написано, он не поддерживает шейдеры

у тебя был вопрос про выгрузку моделей в threejs - я тебе дал её
принцип там везде один и тот же, по этой причине ты не смогла найти доку по выгрузке конкретно анимации, так как эту задачу покрывает дока по выгрузке моделей

2024-02-27 16:04 UTC, pussypistolss commented
@TorinAsakura 
Могу попробовать в синема 4д сделать такую же сферу (без шейдеров), в блендере я эту анимацию кое-как экспортировала в glb формат через аддон, может если в с4д выйдет файл меньше по весу

2024-02-27 17:58 UTC, TorinAsakura commented
> @TorinAsakura Могу попробовать в синема 4д сделать такую же сферу (без шейдеров), в блендере я эту анимацию кое-как экспортировала в glb формат через аддон, может в с4д выйдет файл меньше по весу

сомнительно, но, о-к-эй

Для нас лучший вариант - это управление анимацией на стороне ядра, а не на стороне 3д контейнера.

Если у тебя есть проблемы с экспортом - их не надо избегать, их нужно решать

2024-02-28 07:07 UTC, pussypistolss commented
> Для нас лучший вариант - это управление анимацией на стороне ядра, а не на стороне 3д контейнера.

Та же самая проблема и в с4д, анимация не экспортируется.
> Если у тебя есть проблемы с экспортом - их не надо избегать, их нужно решать

Как мне это решить? Я просмотрела много информации на эту тему, способа экспорта из блендера шейдерной анимации нет. 
Я прошлую анимацию кое-как перенесла в нужный формат, я не знаю сейчас как мне шейдерную экспортировать.

2024-02-28 13:08 UTC, TorinAsakura commented
> > Для нас лучший вариант - это управление анимацией на стороне ядра, а не на стороне 3д контейнера.
> 
> Та же самая проблема и в с4д, анимация не экспортируется.
> 
> > Если у тебя есть проблемы с экспортом - их не надо избегать, их нужно решать
> 
> Как мне это решить? Я просмотрела много информации на эту тему, способа экспорта из блендера шейдерной анимации нет. Я прошлую анимацию кое-как перенесла в нужный формат, я не знаю сейчас как мне шейдерную экспортировать.

https://www.youtube.com/watch?v=e2ntx-fyXaE

@Amiditin @pussypistolss

2024-02-28 13:54 UTC, pussypistolss commented
> сделать способом как на видео, мне нужна шейдерная анимация нашей текущей сферы в формате .glsl

Так как мне ее тебе дать? Экспорт в такие форматы не поддерживается

2024-02-28 13:58 UTC, TorinAsakura commented
@Amiditin @pussypistolss научитесь уже гуглить https://www.reddit.com/r/blender/comments/lj93z8/recreating_blender_shaders_in_glsl/?rdt=53638

Я все эти вещи нахожу за пару-тройку минут. Мы тут переписываемся больше

2024-03-01 04:53 UTC, pussypistolss commented
@Amiditin 


В гиф формате не очень красиво будет смотреться, появляется рябь такая
Сегодня в афтер эффектсе покопаюсь, сделаю видео с прозрачным альфа каналом в одном из этих форматов:
Видео формат AVI, OGG или Quick time c кодеком HuffUV 
Видео формат WebM c кодеком WEBM/VP9
Видео формат Quick time с кодеком QT RLE

<details>

![image](https://github.com/torin-asakura/dream-team/assets/147274591/d50d5cf2-5ec5-4ba0-980e-2208b2d6f213)



https://github.com/torin-asakura/dream-team/assets/147274591/1c896884-1d30-48da-9faf-ccd84563e354

</details>

2024-03-01 10:15 UTC, TorinAsakura commented
> @Amiditin
> 
> В гиф формате не очень красиво будет смотреться, появляется рябь такая Сегодня в афтер эффектсе покопаюсь, сделаю видео с прозрачным альфа каналом в одном из этих форматов: Видео формат AVI, OGG или Quick time c кодеком HuffUV Видео формат WebM c кодеком WEBM/VP9 Видео формат Quick time с кодеком QT RLE

всё это безусловно очень занятно, что вы решили сделать тупо видео с прозрачным фоном, однако вы упускаете вопрос адаптивности. Что будет с вашим видео-объектом на айпэде? Или айфоне? А уж про пользователей андройда у которых одним только моделей с разными разрешениями по тысячу я и говорить не стану.

2024-03-04 08:28 UTC, pussypistolss commented
@Amiditin видео закинула [сюда](https://github.com/torin-asakura/dream-team/pull/119)

2024-04-05 16:56 UTC, TorinAsakura commented
status?

2024-04-06 01:36 UTC, Amiditin commented
> status?

В очереди, приступлю после `delta-doc` и `vanilla/extract`

2024-04-08 10:22 UTC, TorinAsakura commented
> > status?
> 
> В очереди, приступлю после `delta-doc` и `vanilla/extract`

после дельты, но, пред ванилой

2024-04-19 15:38 UTC, merged