Feat/enhancements
torin-asakura/dream-team pull request #78
Opened 2022-08-01 16:46 UTC by brusselboy

2022-08-02 18:04 UTC, TFK70 requested changes
1. На странице контактов не должно быть футера
2. Добавил в [задачу](https://github.com/torin-asakura/dream-team/issues/77) пункт с 404 страницей

2022-08-11 07:32 UTC, TFK70 requested changes
- [ ] Отступы у итемов нестабильные: должны быть 32px, на деле сжимаются до 30px и 31px

![image](https://user-images.githubusercontent.com/62806448/184083576-45591610-a235-4a29-84f2-3e8f67878edb.png)

- [ ] Отступ между итемами в направлениях работы должен быть 32px, на деле он 16px (и в целом там с отступами что-то странной происходит, сам увидишь если через инспектор посмотришь)

![image](https://user-images.githubusercontent.com/62806448/184083911-3fb6db66-3d5d-4ac2-9b05-5397fce19167.png)

- [ ] На странице контактов отступ между ссылками 12px, не 16

![image](https://user-images.githubusercontent.com/62806448/184085122-e8431e13-da88-4152-b7bf-e257554d16b1.png)

2022-08-11 18:02 UTC, TFK70 approved these changes

2022-08-13 08:15 UTC, TorinAsakura commented
Заблюренные картинки очень низкого качества, очень мылят

![Снимок экрана 2022-08-13 в 11 15 26](https://user-images.githubusercontent.com/3940885/184475371-95c34b1e-b171-476f-8cd2-7d8d2f53fce5.png)

2022-08-13 08:17 UTC, TorinAsakura commented
При смене языка меняется высота некоторых блоков, не критично, но лучше бы поправить в следующих итерациях

2022-08-13 08:20 UTC, merged