fix: tag, opengraph
torin-asakura/dream-team pull request #86
Opened 2022-08-12 11:00 UTC by brusselboy

2022-08-12 13:29 UTC, TFK70 requested changes

2022-08-12 13:29 UTC, TFK70 commented on fragments/landing-reviews/src/popover/popover.component.tsx
> +                      <Skill content={title} />
А почему ты не используешь `@ui/tag`? У скилла нет как минимум active стейта

2022-08-12 14:07 UTC, TFK70 approved these changes

2022-08-13 08:24 UTC, TorinAsakura approved these changes

2022-08-13 08:28 UTC, merged